/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package II;

/**
 *
 * @author Farrel
 */
public class biodataSiswaII extends javax.swing.JFrame {

    /**
     * Creates new form biodataSiswaII
     */
    public biodataSiswaII() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jurus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        absent = new javax.swing.JTextField();
        rumah = new javax.swing.JTextField();
        classy = new javax.swing.JComboBox<>();
        rpll = new javax.swing.JRadioButton();
        tkjj = new javax.swing.JRadioButton();
        keluar = new javax.swing.JButton();
        kumpul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));
        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setText("BIODATA SISWA");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(234, 13, 207, 35);

        a.setText("NAMA");
        jPanel1.add(a);
        a.setBounds(69, 74, 34, 16);

        b.setText("ABSEN");
        jPanel1.add(b);
        b.setBounds(69, 114, 38, 16);

        c.setText("KELAS");
        jPanel1.add(c);
        c.setBounds(69, 154, 36, 16);

        d.setText("JURUSAN");
        jPanel1.add(d);
        d.setBounds(69, 195, 53, 16);

        e.setText("ALAMAT");
        jPanel1.add(e);
        e.setBounds(69, 238, 48, 16);
        jPanel1.add(name);
        name.setBounds(150, 71, 214, 22);
        jPanel1.add(absent);
        absent.setBounds(150, 111, 214, 22);
        jPanel1.add(rumah);
        rumah.setBounds(150, 235, 214, 22);

        classy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XR1", "XR2", "XR3", "XR4", "XR5", "XR6", "XR7", "XT1", "XT2", "XT3", "XT4", "XT5", "XT6", "XT7" }));
        jPanel1.add(classy);
        classy.setBounds(150, 151, 214, 22);

        jurus.add(rpll);
        rpll.setText("RPL");
        jPanel1.add(rpll);
        rpll.setBounds(150, 191, 90, 25);

        jurus.add(tkjj);
        tkjj.setText("TKJ");
        jPanel1.add(tkjj);
        tkjj.setBounds(274, 191, 90, 25);

        keluar.setText("exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(508, 234, 71, 25);

        kumpul.setText("submit");
        kumpul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kumpulActionPerformed(evt);
            }
        });
        jPanel1.add(kumpul);
        kumpul.setBounds(508, 191, 71, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 692, 356);
    }// </editor-fold>//GEN-END:initComponents

    private void kumpulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kumpulActionPerformed
        // deklarasi variabel
        String jeneng, absene, juruse, rumahe;
        String kelase = classy.getSelectedItem().toString();
        jeneng = name.getText();
        absene = absent.getText();
        rumahe = rumah.getText();
        
        // jurusan
        if(rpll.isSelected()) {
            juruse = "RPL";
   
        if(classy.getSelectedItem()=="XR1"){
        }
        if(classy.getSelectedItem()=="XR2"){
        }   
        if(classy.getSelectedItem()=="XR3"){
        }
        if(classy.getSelectedItem()=="XR4"){
        }
        if(classy.getSelectedItem()=="XR5"){
        }
        if(classy.getSelectedItem()=="XR6"){
        }
        if(classy.getSelectedItem()=="XR7"){
        }
        }
        else if (tkjj.isSelected()) {
            juruse = "TKJ";
        
        if(classy.getSelectedItem()=="XT1"){
        }
        if(classy.getSelectedItem()=="XT2"){
        }
        if(classy.getSelectedItem()=="XT3"){
        }
        if(classy.getSelectedItem()=="XT4"){
        }
        if(classy.getSelectedItem()=="XT5"){
        }
        if(classy.getSelectedItem()=="XT6"){
        }
        if(classy.getSelectedItem()=="XT7"){
        }
        }
        else {juruse = "";}
        
   new hasilBiodata(jeneng, absene, juruse, rumahe, kelase).setVisible(true);
   dispose();
    }//GEN-LAST:event_kumpulActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
    dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biodataSiswaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biodataSiswaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biodataSiswaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biodataSiswaII.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biodataSiswaII().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JTextField absent;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JComboBox<String> classy;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.ButtonGroup jurus;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kumpul;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton rpll;
    private javax.swing.JTextField rumah;
    private javax.swing.JRadioButton tkjj;
    // End of variables declaration//GEN-END:variables
}
