/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package II;

/**
 *
 * @author Farrel
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }
    String bil = ("");
    double jumlah, bil1, bil2;
    int pilih;
    String bilangan = ("");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ce = new javax.swing.JButton();
        titikbagititik = new javax.swing.JButton();
        c = new javax.swing.JButton();
        del = new javax.swing.JButton();
        pitu = new javax.swing.JButton();
        wolu = new javax.swing.JButton();
        songo = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        papat = new javax.swing.JButton();
        siji = new javax.swing.JButton();
        minplus = new javax.swing.JButton();
        persen = new javax.swing.JButton();
        akaran = new javax.swing.JButton();
        pangkatloro = new javax.swing.JButton();
        limo = new javax.swing.JButton();
        enem = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        loro = new javax.swing.JButton();
        telu = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txt_hasil = new javax.swing.JTextField();
        samadengan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-Calc");
        getContentPane().setLayout(null);

        ce.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ce.setText("CE");
        ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceActionPerformed(evt);
            }
        });
        getContentPane().add(ce);
        ce.setBounds(24, 221, 90, 65);

        titikbagititik.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        titikbagititik.setText("÷");
        titikbagititik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikbagititikActionPerformed(evt);
            }
        });
        getContentPane().add(titikbagititik);
        titikbagititik.setBounds(298, 221, 80, 65);

        c.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(126, 221, 80, 65);

        del.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        del.setText("DEL");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        getContentPane().add(del);
        del.setBounds(212, 221, 80, 65);

        pitu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pitu.setText("7");
        pitu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pituActionPerformed(evt);
            }
        });
        getContentPane().add(pitu);
        pitu.setBounds(24, 299, 90, 65);

        wolu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        wolu.setText("8");
        wolu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                woluActionPerformed(evt);
            }
        });
        getContentPane().add(wolu);
        wolu.setBounds(126, 299, 80, 65);

        songo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        songo.setText("9");
        songo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songoActionPerformed(evt);
            }
        });
        getContentPane().add(songo);
        songo.setBounds(212, 299, 80, 65);

        kali.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        kali.setText("X");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        getContentPane().add(kali);
        kali.setBounds(298, 299, 79, 65);

        papat.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        papat.setText("4");
        papat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papatActionPerformed(evt);
            }
        });
        getContentPane().add(papat);
        papat.setBounds(24, 377, 90, 60);

        siji.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        siji.setText("1");
        siji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sijiActionPerformed(evt);
            }
        });
        getContentPane().add(siji);
        siji.setBounds(24, 450, 90, 60);

        minplus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        minplus.setText("±");
        minplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minplusActionPerformed(evt);
            }
        });
        getContentPane().add(minplus);
        minplus.setBounds(24, 523, 90, 60);

        persen.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        getContentPane().add(persen);
        persen.setBounds(24, 148, 90, 60);

        akaran.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        akaran.setText("√");
        akaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akaranActionPerformed(evt);
            }
        });
        getContentPane().add(akaran);
        akaran.setBounds(126, 148, 79, 60);

        pangkatloro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pangkatloro.setText("x^2");
        pangkatloro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatloroActionPerformed(evt);
            }
        });
        getContentPane().add(pangkatloro);
        pangkatloro.setBounds(212, 148, 79, 60);

        limo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        limo.setText("5");
        limo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limoActionPerformed(evt);
            }
        });
        getContentPane().add(limo);
        limo.setBounds(126, 377, 79, 60);

        enem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        enem.setText("6");
        enem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enemActionPerformed(evt);
            }
        });
        getContentPane().add(enem);
        enem.setBounds(212, 377, 79, 60);

        kurang.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        getContentPane().add(kurang);
        kurang.setBounds(298, 377, 79, 60);

        loro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        loro.setText("2");
        loro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loroActionPerformed(evt);
            }
        });
        getContentPane().add(loro);
        loro.setBounds(126, 450, 79, 60);

        telu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        telu.setText("3");
        telu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teluActionPerformed(evt);
            }
        });
        getContentPane().add(telu);
        telu.setBounds(212, 450, 79, 60);

        tambah.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(298, 450, 79, 60);

        nol.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        getContentPane().add(nol);
        nol.setBounds(123, 523, 82, 60);

        koma.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        getContentPane().add(koma);
        koma.setBounds(212, 523, 79, 60);

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(51, 51, 51)));
        jPanel1.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 530, 70, 30);

        txt_hasil.setEditable(false);
        txt_hasil.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(txt_hasil);
        txt_hasil.setBounds(20, 22, 360, 100);

        samadengan.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel1.add(samadengan);
        samadengan.setBounds(300, 150, 79, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 630);

        setBounds(0, 0, 419, 672);
    }// </editor-fold>//GEN-END:initComponents

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
        // TODO add your handling code here:
        switch (pilih) {
            case 1:
                bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
                jumlah = bil1 + bil2;
                bilangan = Double.toString(jumlah);
                break;
            case 2:
                bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
                jumlah = bil1 - bil2;
                bilangan = Double.toString(jumlah);
                break;
            case 3:
                bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
                jumlah = bil1 * bil2;
                bilangan = Double.toString(jumlah);
                break;
            case 4:
                bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
                jumlah = bil1 / bil2;
                bilangan = Double.toString(jumlah);
                break;
            case 5:
                bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
                jumlah = bil1 % bil2;
                bilangan = Double.toString(jumlah);
                break;
            case 6:
            bil2 = Double.parseDouble(String.valueOf(txt_hasil.getText()));
                jumlah = bil1 * bil1;
                bilangan = Double.toString(jumlah);
                break;

        }
        txt_hasil.setText(bilangan);

    }//GEN-LAST:event_samadenganActionPerformed

    private void woluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_woluActionPerformed
        // TODO add your handling code here:

        bilangan += "8";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_woluActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        txt_hasil.getText().length();
        StringBuilder all = new StringBuilder(txt_hasil.getText());
        char end = all.charAt(all.length()-1);
        all.deleteCharAt((all.length()-1));
        txt_hasil.setText(all.toString());
    }//GEN-LAST:event_delActionPerformed

    private void sijiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sijiActionPerformed
        // TODO add your handling code here:      
        bilangan += "1";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_sijiActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:

        bilangan += "0";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_nolActionPerformed

    private void loroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loroActionPerformed
        // TODO add your handling code here:

        bilangan += "2";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_loroActionPerformed

    private void teluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teluActionPerformed
        // TODO add your handling code here:

        bilangan += "3";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_teluActionPerformed

    private void papatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papatActionPerformed
        // TODO add your handling code here:

        bilangan += "4";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_papatActionPerformed

    private void limoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limoActionPerformed
        // TODO add your handling code here:

        bilangan += "5";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_limoActionPerformed

    private void enemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enemActionPerformed
        // TODO add your handling code here:

        bilangan += "6";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_enemActionPerformed

    private void pituActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pituActionPerformed
        // TODO add your handling code here:

        bilangan += "7";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_pituActionPerformed

    private void songoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songoActionPerformed
        // TODO add your handling code here:

        bilangan += "9";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_songoActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
        bil1 = 0.0;
        bil2 = 0.0;
        jumlah = 0.0;
        bilangan = "";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_cActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        txt_hasil.setText("+");
        bilangan = "";
        pilih = 1;
    }//GEN-LAST:event_tambahActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        txt_hasil.setText("-");
        bilangan = "";
        pilih = 2;
    }//GEN-LAST:event_kurangActionPerformed

    private void minplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minplusActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(txt_hasil.getText()));
        ops = ops * (-1);
        txt_hasil.setText(String.valueOf(ops));
        pilih = 0;
    }//GEN-LAST:event_minplusActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
        // TODO add your handling code here:
        bilangan += ".";
        txt_hasil.setText(bilangan);
    }//GEN-LAST:event_komaActionPerformed

    private void akaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akaranActionPerformed
        // TODO add your handling code here:
double ops = Double.parseDouble(String.valueOf(txt_hasil.getText()));
        ops = Math.sqrt(ops);
        txt_hasil.setText(String.valueOf(ops));
    }//GEN-LAST:event_akaranActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        txt_hasil.setText("*");
        bilangan = "";
        pilih = 3;
    }//GEN-LAST:event_kaliActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        txt_hasil.setText("% ");
        bilangan = "";
        pilih = 5;
    }//GEN-LAST:event_persenActionPerformed

    private void titikbagititikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikbagititikActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        txt_hasil.setText("/");
        bilangan = "";
        pilih = 4;
    }//GEN-LAST:event_titikbagititikActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceActionPerformed
        // TODO add your handling code here:
        txt_hasil.setText("");
    }//GEN-LAST:event_ceActionPerformed

    private void pangkatloroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatloroActionPerformed
        // TODO add your handling code here:
        bil1 = Double.parseDouble(bilangan);
        txt_hasil.setText("^");
        bilangan = "";
pilih=6;
    }//GEN-LAST:event_pangkatloroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        ;//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akaran;
    private javax.swing.JButton c;
    private javax.swing.JButton ce;
    private javax.swing.JButton del;
    private javax.swing.JButton enem;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton limo;
    private javax.swing.JButton loro;
    private javax.swing.JButton minplus;
    private javax.swing.JButton nol;
    private javax.swing.JButton pangkatloro;
    private javax.swing.JButton papat;
    private javax.swing.JButton persen;
    private javax.swing.JButton pitu;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton siji;
    private javax.swing.JButton songo;
    private javax.swing.JButton tambah;
    private javax.swing.JButton telu;
    private javax.swing.JButton titikbagititik;
    private javax.swing.JTextField txt_hasil;
    private javax.swing.JButton wolu;
    // End of variables declaration//GEN-END:variables
}
