/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Farrel
 */
public class lat2 extends javax.swing.JFrame {

    /**
     * Creates new form lat2
     */
    public lat2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanjurusan = new javax.swing.ButtonGroup();
        pilihanhobi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        isiNama = new javax.swing.JTextField();
        RBRPL = new javax.swing.JRadioButton();
        RBTKJ = new javax.swing.JRadioButton();
        isiAbsen = new javax.swing.JTextField();
        hProg = new javax.swing.JCheckBox();
        hAnim = new javax.swing.JCheckBox();
        hDesign = new javax.swing.JCheckBox();
        hVideo = new javax.swing.JCheckBox();
        bSubmit = new javax.swing.JButton();
        rRemove = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hsl = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Square721 BT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIODATA");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(214, 37, 321, 38);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(108, 91, 33, 16);

        jLabel3.setText("Absen");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(108, 126, 35, 16);

        jLabel4.setText("Jurusan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(108, 166, 44, 16);

        jLabel5.setText("Hobi");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(108, 209, 25, 16);
        jPanel1.add(isiNama);
        isiNama.setBounds(214, 88, 321, 22);

        pilihanjurusan.add(RBRPL);
        RBRPL.setText("RPL");
        jPanel1.add(RBRPL);
        RBRPL.setBounds(214, 162, 49, 25);

        pilihanjurusan.add(RBTKJ);
        RBTKJ.setText("TKJ");
        jPanel1.add(RBTKJ);
        RBTKJ.setBounds(486, 162, 49, 25);
        jPanel1.add(isiAbsen);
        isiAbsen.setBounds(214, 123, 321, 22);

        pilihanhobi.add(hProg);
        hProg.setText("Programming");
        jPanel1.add(hProg);
        hProg.setBounds(214, 205, 105, 25);

        pilihanhobi.add(hAnim);
        hAnim.setText("Animator");
        jPanel1.add(hAnim);
        hAnim.setBounds(432, 205, 81, 25);

        pilihanhobi.add(hDesign);
        hDesign.setText("Designer");
        jPanel1.add(hDesign);
        hDesign.setBounds(214, 248, 79, 25);

        pilihanhobi.add(hVideo);
        hVideo.setText("Video Editing");
        jPanel1.add(hVideo);
        hVideo.setBounds(432, 248, 103, 25);

        bSubmit.setText("Submit");
        bSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(bSubmit);
        bSubmit.setBounds(214, 310, 73, 25);

        rRemove.setText("Remove");
        rRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(rRemove);
        rRemove.setBounds(402, 310, 79, 25);

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel1.add(bExit);
        bExit.setBounds(311, 353, 53, 25);

        jLabel6.setText("Hasil");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(214, 385, 27, 16);

        hsl.setColumns(20);
        hsl.setRows(5);
        jScrollPane1.setViewportView(hsl);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(214, 408, 321, 96);

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\info dota 2\\c7-cover-1-850x491.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(180, 20, 610, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 842, 572);
    }// </editor-fold>//GEN-END:initComponents

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void rRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rRemoveActionPerformed
        // TODO add your handling code here:
        isiNama.setText(" ");
        isiAbsen.setText(" ");
        pilihanjurusan.clearSelection();
        hsl.setText("");
        hProg.setSelected(false);
        hAnim.setSelected(false);
        hDesign.setSelected(false);
        hVideo.setSelected(false);
    }//GEN-LAST:event_rRemoveActionPerformed

    private void bSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSubmitActionPerformed
        // TODO add your handling code here:
        String nama = isiNama.getText();
        String absen = isiAbsen.getText();
        String jurusan;
        String hobi = "";
        
        // UNtuk pilihan jurusan
        if(RBRPL.isSelected())
            jurusan ="RPL";
        else if(RBTKJ.isSelected())
            jurusan = "TKJ";
        else
            jurusan = " ";
        
        // Untuk pilihan checkbox
        if(hAnim.isSelected())
            hobi += hAnim.getText()+", ";
        if (hDesign.isSelected())
            hobi +=hDesign.getText()+", ";
        if (hProg.isSelected());
            hobi+=hProg.getText()+", ";
        if (hVideo.isSelected());
            hobi+=hVideo.getText()+", ";
            
        // Untuk Hasil
        hsl.setText("Nama anda : " + nama+ "\nAbsen anda : "+ absen + "\nJurusan anda : " +jurusan+ "\nHobi anda : "+hobi );
                
    }//GEN-LAST:event_bSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lat2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBRPL;
    private javax.swing.JRadioButton RBTKJ;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bSubmit;
    private javax.swing.JCheckBox hAnim;
    private javax.swing.JCheckBox hDesign;
    private javax.swing.JCheckBox hProg;
    private javax.swing.JCheckBox hVideo;
    private javax.swing.JTextArea hsl;
    private javax.swing.JTextField isiAbsen;
    private javax.swing.JTextField isiNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup pilihanhobi;
    private javax.swing.ButtonGroup pilihanjurusan;
    private javax.swing.JButton rRemove;
    // End of variables declaration//GEN-END:variables
}
