/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Farrel
 */
public class Latihan03 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan03
     */
    public Latihan03() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        height = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        hit = new javax.swing.JButton();
        kel = new javax.swing.JButton();
        ul = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tanya = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");

        jLabel6.setText("Berat badan ideal anda adalah : ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(null);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 33, 16);

        jLabel3.setText("Berat Badan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(89, 131, 69, 16);

        jLabel4.setText("Tinggi Badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(89, 163, 74, 16);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(89, 189, 77, 16);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(150, 90, 470, 22);

        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        jPanel1.add(weight);
        weight.setBounds(189, 128, 470, 22);
        jPanel1.add(height);
        height.setBounds(189, 160, 470, 22);

        jenisKelamin.add(male);
        male.setText("Laki-laki");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male);
        male.setBounds(304, 185, 75, 25);

        jenisKelamin.add(female);
        female.setText("perempuan");
        jPanel1.add(female);
        female.setBounds(487, 185, 93, 25);

        hit.setText("Hitung");
        hit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitActionPerformed(evt);
            }
        });
        jPanel1.add(hit);
        hit.setBounds(304, 241, 69, 25);

        kel.setText("Keluar");
        kel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelActionPerformed(evt);
            }
        });
        jPanel1.add(kel);
        kel.setBounds(590, 241, 69, 25);

        ul.setText("Ulangi");
        ul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulActionPerformed(evt);
            }
        });
        jPanel1.add(ul);
        ul.setBounds(442, 241, 67, 25);

        jLabel7.setText("Berat badan ideal anda Adalah : ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(89, 287, 188, 16);

        ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idealActionPerformed(evt);
            }
        });
        jPanel1.add(ideal);
        ideal.setBounds(289, 284, 53, 22);

        jLabel8.setText("kg");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 287, 13, 16);

        jLabel9.setText("Hasil analisa kesehatan");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(89, 342, 133, 16);

        tanya.setText("?");
        tanya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanyaActionPerformed(evt);
            }
        });
        jPanel1.add(tanya);
        tanya.setBounds(89, 371, 570, 22);

        saran.setText("Saran?");
        jPanel1.add(saran);
        saran.setBounds(89, 411, 570, 22);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CEK KESEHATAN");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 40, 120, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 800, 624);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

    }//GEN-LAST:event_nameActionPerformed

    private void idealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idealActionPerformed

    }//GEN-LAST:event_idealActionPerformed
   
    private void tanyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanyaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanyaActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void hitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitActionPerformed
        // TODO add your handling code here:
        double t, b, h = 0;

t = Double.valueOf(height.getText());
b = Double.valueOf(weight.getText());
String nm = name.getText();

// Pilihan jenis kelamin
if(male.isSelected()){
h = (t-100);
} 
else if (female.isSelected()){
        h = (t-104);
}
String id = Double.toString(h);

// Logika ntuk analisa hasil kesehatan
if (h>b){
    ideal.setText(id);
    tanya.setText("Maaf "+ nm + ", anda kekurangan berat badan.");
    saran.setText("Makan yang banyak dan bergizi.");
}
else if(h<b){
    ideal.setText(id);
    tanya.setText("Maaf "+ nm + ", anda Kelebihan berat badan.");
    saran.setText("Kurangi porsi makan dan olahraga teratur.");
}
else {
    ideal.setText(id);
    tanya.setText("Selamat" + nm + ", anda ideal.");
    saran.setText("Terus pertahankan dan tetap semangat.");
}
    }//GEN-LAST:event_hitActionPerformed

    private void ulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulActionPerformed
        // TODO add your handling code here:
        name.setText("");
        height.setText("");
        weight.setText("");
        ideal.setText("");
        tanya.setText("");
        saran.setText("");
        jenisKelamin.clearSelection();
    }//GEN-LAST:event_ulActionPerformed

    private void kelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelActionPerformed
dispose();
    }//GEN-LAST:event_kelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan03.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan03().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField height;
    private javax.swing.JButton hit;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JButton kel;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tanya;
    private javax.swing.JButton ul;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
